const works = [
  {
    startDate: 'Nov 2020',
    endDate: 'Now',
    name: 'Datia',
    role: 'Software Engineer',
    description: 'Datia helps you automate your sustainability workflows and manage the EU Taxonomy and Sustainable Finance Disclosure Regulation.',
    type: 'job',
    url: 'https://www.linkedin.com/company/datiaapp/',
    image: '../images/datia.png',
    gradient: 'linear-gradient(-70deg, rgb(80 51 251), rgb(118 47 225))',
  },
  {
    startDate: 'Aug 2020',
    endDate: 'Nov 2020',
    name: 'Rather',
    role: 'Front-end developer',
    description: 'We all like to give recommendations about certain aspects of our lives that we enjoy, that we value or use. And on those aspects that we remain in doubt, we like to consult people we know can give us valuable recommendations.',
    type: 'job',
    url: 'https://www.linkedin.com/company/friends-recommendations/',
    image: '../images/rather.png',
    gradient: 'linear-gradient(-70deg,#4c32ea,#4d32ed)',
  },
  {
    startDate: 'April 2022',
    endDate: 'Now',
    name: 'Runny',
    role: 'Creator',
    description: 'Runny is a web application to see and add restaurant digital menus easily to get a previous knowledge about the prices and dishes of the place to go. Currently is only working in Argentina.',
    type: 'project',
    url: 'https://www.runny.me',
    image: '../images/runny.png',
    gradient: 'linear-gradient(-70deg,#24ad5e,#2e9564)',
  },
  {
    startDate: 'May 2020',
    endDate: 'Now',
    name: 'Bitflix',
    role: 'Creator',
    description: "Bitflix is an open source web application that allows you to watch movies and TV Shows through torrents directly in your browser. I developed the UI and also some API's to get subtitles and videos.",
    type: 'project',
    url: 'https://bitflixapp.com',
    image: '../images/bitflix.png',
    gradient: 'linear-gradient(-70deg,#286bcc,#2666c4)',
  },
  {
    startDate: 'July 2021',
    endDate: 'Now',
    name: 'Storm',
    role: 'Creator',
    description: "Storm comes with the idea of change the way we see torrent clients. Traditional clients always have those tables with data you don't need to see. Storm gives you just the necessary features with a beautiful UI/UX. I built the entire application using different technologies like Electron, Node, React, socket.io and more.",
    type: 'project',
    url: 'https://storm-web.vercel.app/',
    image: '../images/storm.png',
    gradient: 'linear-gradient(-70deg,#3a60d8,#3859c5)',
  },
  {
    startDate: 'July 2020',
    endDate: 'Now',
    name: 'NextTime',
    role: 'Creator',
    description: 'NextTime is an open source web application that allows you to know the time in any country in the world, either now or in the future.',
    type: 'project',
    url: 'https://nexttime.now.sh',
    image: '../images/nexttime.png',
    gradient: 'linear-gradient(-70deg,#1364be,#7b3dff)',
  },
];

export default works;
